contact/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='contact'
urlpatterns = [

    path('contact',views.contact,name='contact'),

]

listings/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='listings'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
#display of info urls
    path('deptlisting',views.departments,name='deptlisting'),
    path('buglisting',views.buglist,name='buglisting'),
    path('statuslisting',views.statuslist,name='statuslisting'),
    path('typelisting',views.typelist,name='typelisting'),
    path('projectlisting',views.projectlist,name='projectlisting'),
    path('userlisting',views.userlist,name='userlisting'),
#create urls
    path('add_bug/',views.addBug,name='add_bug'),
    path('add_type/',views.addType,name='add_type'),
    path('add_status/',views.addStatus,name='add_status'),
    path('add_dept/',views.addDept,name='add_dept'),
    path('add_project/',views.addProject,name='add_project'),
    path('add_user/',views.addUser,name='add_user'),
#update urls
    path('update_bug/<str:pk>/',views.updateBug,name='update_bug'),
    path('update_type/<str:pk>/',views.updateType,name='update_type'),
    path('update_status/<str:pk>/',views.updateStatus,name='update_status'),
    path('update_project/<str:pk>/',views.updateProject,name='update_project'),
    path('update_user/<str:pk>/',views.updateUser,name='update_user'),
    path('update_dept/<str:pk>/',views.updateDept,name='update_dept'),
#delete urls
    path('delete_bug/<str:pk>/',views.deleteBug,name='delete_bug'),
    path('delete_type/<str:pk>/',views.deleteType,name='delete_type'),
    path('delete_status/<str:pk>/',views.deleteStatus,name='delete_status'),
    path('delete_project/<str:pk>/',views.deleteProject,name='delete_project'),
    path('delete_user/<str:pk>/',views.deleteUser,name='delete_user'),
    path('delete_dept/<str:pk>/',views.deleteDept,name='delete_dept'),

    ]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('contact',views.ContactPage.as_view(),name='contact'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('listings/',include('listings.urls',namespace='listings')),
    path('contact/',include('contact.urls',namespace='contact')),










    path('myaccount',views.UserAccount.as_view(),name='myaccount'),
    path('passwordchange',views.ChangePassword.as_view(),name='changepassword'),



]

listings/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Status(models.Model):
    status_id = models.AutoField(primary_key=True)
    status_title = models.CharField(max_length=255, default = '',)
    status_description = models.CharField(max_length=255, default = '',blank=True)
    def __str__(self):
        return self.status_title

class BugType(models.Model):
    type_id = models.AutoField(primary_key=True)
    type_title = models.CharField(max_length=255,default = '')
    type_description = models.CharField(max_length=255, default = '',blank=True)
    def __str__(self):
        return self.type_title

class Department(models.Model):
    department_id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=255,default = '')
    department_location = models.CharField(max_length=255,default = '')
    def __str__(self):
        return self.department_name

class Project(models.Model):
    project_id = models.AutoField(primary_key=True)
    project_lead_name = models.CharField(max_length=255, default = '')
    project_title = models.CharField(max_length=255, default = '',)
    project_submission_date = models.CharField(max_length=255, default = '')
    project_duration = models.CharField(max_length=255, default = '')
    project_email = models.CharField(max_length=255, default = '')
    project_department = models.CharField(max_length=255, default = '',)
    project_client_name = models.CharField(max_length=255, default = '',blank=True)
    def __str__(self):
        return self.project_title

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=255, default = '')
    role = models.CharField(max_length=255, default = '',)
    user_mobile = models.CharField(max_length=255, default = '')
    user_email = models.CharField(max_length=255, default = '')
    user_dob = models.CharField(max_length=255, default = '')
    user_image = models.CharField(max_length=255, default = '',blank=True)
    def __str__(self):
        return self.user_name

class Bug(models.Model):
    bug_id = models.AutoField(primary_key=True)
    user_reporting = models.CharField(max_length=255, default = '')
    user_number = models.CharField(max_length=255, default = "")
    user_email = models.CharField(max_length=255, default = '')
    bug_name = models.CharField(max_length=255, default = "", null=True)
    bug_project = models.ForeignKey(Project, null=True, on_delete=models.SET_NULL)
    bug_date = models.CharField(max_length=255, default = '')
    bug_level = models.CharField(max_length=255, default = '')
    bug_priority = models.ForeignKey(BugType, null=True, on_delete=models.SET_NULL)
    bug_status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    bug_description = models.TextField(default = "")
    bug_cost = models.CharField(max_length=255, default = "",blank=True)
    bug_image = models.CharField(max_length=255, default="",blank=True)
    bug_specifications = models.CharField(max_length=255, default = "",blank=True)
    def __str__(self):
        return self.bug_name

listings/forms.py
from django.forms import ModelForm
from .models import *

# meta data for CRUD

class BugForm(ModelForm):
    class Meta:
        model = Bug
        fields = ['bug_name','bug_project','bug_date',
                'bug_priority','bug_status','bug_description',
                'user_reporting','user_email','user_number','bug_image']

class BugTypeForm(ModelForm):
    class Meta:
        model = BugType
        fields = ['type_title',
                'type_description']

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['status_title','status_description']


class DeptForm(ModelForm):
    class Meta:
        model = Department
        fields = ['department_name','department_location']

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['project_lead_name','project_title','project_submission_date','project_duration',
                    'project_client_name','project_email','project_department']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['user_image','user_name','role','user_mobile','user_email','user_dob']


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = ['department_name','department_location']

listings/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.db import connection
from .forms import *

from .models import Status,BugType,Department,Project,User,Bug

def home(request):
    context = locals()
    template = 'home.html'
    return render(request,template,context)

#
# listing functions

def departments(request):
        departments = Department.objects.all()
        print("------------------------------------------")
        for i in departments:
            print(i.department_id)
        print("------------------------------------------")
        return render(request,'listings/departmentdetails.html', {'departments':departments})


def buglist(request):
    buglist = Bug.objects.all()
    print("------------------------------------------")
    for i in buglist:
        print(i.bug_id)
    print("------------------------------------------")
    return render(request,'listings/buglisting.html',{'buglist':buglist})


def statuslist(request):
    statuslist = Status.objects.all()
    print("------------------------------------------")
    for i in statuslist:
        print(i.status_id)
    print("------------------------------------------")
    return render(request,'listings/statusdetails.html',{'statuslist':statuslist})


def typelist(request):
    typelist = BugType.objects.all()
    print("------------------------------------------")
    for i in typelist:
        print(i.type_id)
    print("------------------------------------------")
    return render(request,'listings/typedetails.html',{'typelist':typelist})


def projectlist(request):
    projectlist = Project.objects.all()
    print("------------------------------------------")
    for i in projectlist:
        print(i.project_id)
    print("------------------------------------------")
    return render(request,'listings/projectdetails.html',{'projectlist':projectlist})


def userlist(request):
    userlist = User.objects.all()
    print("------------------------------------------")
    for i in userlist:
        print(i.user_id)
    print("------------------------------------------")
    return render(request,'listings/userdetails.html',{'userlist':userlist})


# create functions

def addBug(request):

    form = BugForm()
    if request.method =='POST':
        # print('printing POST', request.POST)
        form = BugForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/listings/buglisting')

    context = {'addbug':form}
    return render(request, 'listings/add_bug.html', context)

def addType(request):

    form = BugTypeForm()
    if request.method == 'POST':
        # print('printing POST', request.POST)
        form = BugTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/listings/typelisting')

    context = {'addtype':form}
    return render(request, 'listings/add_type.html', context)


def addStatus(request):

    form = StatusForm()
    if request.method == "POST":
        # print('printing POST', request.POST)
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/listings/statuslisting')

    context = {'addstatus':form}
    return render(request, 'listings/add_status.html', context)

def addDept(request):
    form = DeptForm()
    if request.method == "POST":
        form = DeptForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/listings/deptlisting')

    context = {'adddept':form}
    return render (request, 'listings/add_dept.html', context)

def addProject(request):
    form = ProjectForm()
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/listings/projectlisting')

    context = {'addproject':form}
    return render (request, 'listings/add_project.html', context)

def addUser(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/listings/userlisting')

    context = {'adduser':form}
    return render (request, 'listings/add_user.html', context)

#update functions

def updateBug(request, pk):

    updatebug = Bug.objects.get(bug_name=pk)
    form = BugForm(instance=updatebug)

    if request.method == 'POST':
        form = BugForm(request.POST, instance=updatebug)
        if form.is_valid():
            form.save()
        return redirect('/listings/buglisting')


    context = {'addbug':form}
    return render(request,'listings/add_bug.html/',context)

def updateType(request, pk):

    updatetype = BugType.objects.get(type_id=pk)
    form = BugTypeForm(instance=updatetype)

    if request.method == 'POST':
        form = BugTypeForm(request.POST, instance=updatetype)
        if form.is_valid():
            form.save()
        return redirect('/listings/typelisting')

    context = {'addtype':form}
    return render(request,'listings/add_type.html/', context)

def updateStatus(request, pk):

    updatestatus = Status.objects.get(status_id=pk)
    form = StatusForm(instance=updatestatus)

    if request.method == "POST":
        form = StatusForm(request.POST, instance = updatestatus)
        if form.is_valid():
            form.save()
        return redirect('/listings/statuslisting')

    context = {'addstatus':form}
    return render (request, 'listings/add_status.html/', context)

def updateProject(request, pk):

    updateproject = Project.objects.get(project_id=pk)
    form = ProjectForm(instance = updateproject)

    if request.method == "POST":
        form = ProjectForm(request.POST, instance = updateproject)
        if form.is_valid():
            form.save()
        return redirect('/listings/projectlisting')

    context = {'addproject':form}
    return render (request, 'listings/add_project.html/', context)

def updateUser(request, pk):

    updateuser = User.objects.get(user_id=pk)
    form = UserForm(instance = updateuser)

    if request.method == "POST":
        form = UserForm(request.POST,instance=updateuser)
        if form.is_valid():
            form.save()
        return redirect('/listings/userlisting')

    context = {'adduser': form}
    return render (request, 'listings/add_user.html/', context)

def updateDept(request, pk):

    updatedept = Department.objects.get(department_id=pk)
    form = DepartmentForm(instance = updatedept)

    if request.method == "POST":
        form = DepartmentForm(request.POST,instance=updatedept)
        if form.is_valid():
            form.save()
        return redirect('/listings/deptlisting')

    context = {'adddept': form}
    return render (request, 'listings/add_dept.html/', context)


#delete methods

def deleteBug(request, pk):
    deletebug = Bug.objects.get(bug_name=pk)
    if request.method == "POST":
        deletebug.delete()
        return redirect ('/listings/buglisting')


    context = {'deletebug':deletebug}
    return render(request, 'templates/delete/deletebug.html', context)

def deleteType(request, pk):
    deletetype = BugType.objects.get(type_title=pk)
    if request.method == "POST":
        deletetype.delete()
        return redirect ('/listings/typelisting')

    context = {'deletetype':deletetype}
    return render(request, 'templates/delete/deletetype.html', context)

def deleteStatus(request, pk):
    deletestatus = Status.objects.get(status_id=pk)
    if request.method == "POST":
        deletestatus.delete()
        return redirect ('/listings/statuslisting')

    context = {'deletestatus':deletestatus}
    return render (request, 'templates/delete/deletestatus.html', context)

def deleteProject(request, pk):
    deleteproject = Project.objects.get(project_id=pk)
    if request.method == "POST":
        deleteproject.delete()
        return redirect ('/listings/projectlisting')

    context = {'deleteproject':deleteproject}
    return render (request, 'templates/delete/deleteproject.html', context)

def deleteUser(request, pk):
    deleteuser = User.objects.get(user_id=pk)
    if request.method == "POST":
        deleteuser.delete()
        return redirect ('/listings/userlisting')

    context = {'deleteuser':deleteuser}
    return render (request, 'templates/delete/deleteuser.html', context)

def deleteDept(request, pk):
    deletedept = Department.objects.get(department_id=pk)
    if request.method == "POST":
        deletedept.delete()
        return redirect ('/listings/deptlisting')

    context = {'deletedept':deletedept}
    return render (request, 'templates/delete/deletedept.html', context)

listings/templates/listings/add_bug.html
{% extends 'base.html' %} {% block content %}
<!-- banner -->
<div class="banner">
  <h1 id='bannerLogo'>ADD BUG</h1>
</div>

<!-- form -->
<div class="">
  <form class='addclass1' action="" method="POST">
    {% csrf_token %}
    {{addbug}}
    <input type="submit" name="submit" >
  </form>

</div>


{% endblock content %}

listings/templates/listings/add_dept.html
{% extends 'base.html' %} {% block content %}


<div class="banner">
  <h1 id='bannerLogo'>ADD DEPARTMENT</h1>
</div>


<!-- form -->
<form class='addclass'action="" method="POST">
  {% csrf_token %}
  {{adddept}}
  <input type="submit" name="submit" >
</form>

<!--container end-->
{% endblock content %}

listings/templates/listings/add_project.html
{% extends 'base.html' %} {% block content %}
<!--breadcrumbs start-->
<div class="banner">
  <h1 id='bannerLogo'>ADD PROJECT</h1>
</div>


<!-- form -->
<form class='addclass2' action="" method="POST">
  {% csrf_token %}
  {{addproject}}
  <input type="submit" name="submit" >
</form>

<br>
<!--container end-->
{% endblock content %}

listings/templates/listings/add_status.html
{% extends 'base.html' %} {% block content %}


<div class="banner">
  <h1 id='bannerLogo'>ADD STATUS</h1>
</div>

<!-- form -->
<form class='addclass' action="" method="POST">
  {% csrf_token %}
  {{addstatus}}
  <input type="submit" name="submit" >
</form>

<br>


<!--container end-->
{% endblock content %}

listings/templates/listings/add_type.html
{% extends 'base.html' %} {% block content %}

<!--breadcrumbs start-->
<div class="banner">
  <h1 id='bannerLogo'>ADD TYPE</h1>
</div>

<!-- form -->
<form  class='addclass' action="" method="POST">
  {% csrf_token %}
  {{addtype}}
  <input type="submit" name="submit" >
</form>

<br>

<!--container end-->
{% endblock content %}

listings/templates/listings/add_user.html
{% extends 'base.html' %} {% block content %}

<div class="banner">
  <h1 id='bannerLogo'>REGISTER</h1>
</div>

<!-- form -->
<form  class='addclass3' action="" method="POST">
  {% csrf_token %}
  {{adduser}}
  <input type="submit" name="submit" >
</form>

<br>

<!--container end-->
{% endblock content %}

listings/templates/listings/buglisting.html
{% extends 'base.html' %}
{% block content %}
<script>
$(document).on("click", ".delete-dialog", function () {
  var id = $(this).data('id');
	$("#recordID").val( id );
});
function delete_record(bug_id)
{
	location.href = "/bug/delete/"+$("#recordID").val();
}
</script>

<div class="banner">
  <h1 id='bannerLogo'>ALL BUGS REPORT</h1>
</div>


<div id='listingadd' class="container">
		<div class="row">
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
		  {% endif %}
		  <div class="col-lg-12">
			<form name="frm" action="lib/bug.php" method="post">
			  <section class="panel">
				  <table class="table table-striped table-advance table-hover" style="color:#000000">
				   <tbody>
							<tr>
								<th style="background-color:#003d65; color:#FFFFFF;">ID</th>

								<th style="background-color:#003d65; color:#FFFFFF;">Bug Title</th>
								<th style="background-color:#003d65; color:#FFFFFF;">User Name</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Email</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Contact</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Type</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Status</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Action</th>
							</tr>
							{% for i in buglist %}
								<tr>
                  <td>{{i.bug_id}}</td>

                  <td>{{i.bug_name}}</td>
                  <td>{{i.user_reporting}}</td>
                  <td>{{i.user_email}}</td>
                  <td>{{i.user_number}}</td>
                  <td>{{i.bug_priority}}</td>
                  <td>{{i.bug_status}}</td>
                  <td>
                    <div class="btn-group">

                        <a href="{% url 'listings:update_bug' i.bug_name%}" class="btn btn-success">Edit</a>

                        <a class="delete-dialog btn btn-danger"  method="POST" href="{% url 'listings:delete_bug' i.bug_name%}">Delete</a>
                  </td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				<input type="hidden" name="act" />
			  <input type="hidden" name="bug_id" id="recordID" />
	</form>
</div>
</div>
</div>
</div>
{% endblock content %}

listings/templates/listings/departmentdetails.html
{% extends 'base.html' %}
{% block content %}
<script>
$(document).on("click", ".delete-dialog", function () {
  var id = $(this).data('id');
	$("#recordID").val( id );
});
function delete_record(department_id)
{
	location.href = "/department/delete/"+$("#recordID").val();
}
</script>

    <!--breadcrumbs start-->
    <div class="banner">
      <h1 id='bannerLogo'>DEPARTMENT DETAILS</h1>
    </div>

    <!--breadcrumbs end-->

 <div  id='listingadd' class="container">
		<div class="row">
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
		  {% endif %}
		  <div class="col-lg-12">
			<form name="frm" action="" method="post">
			  <section class="panel">
				  <table class="table table-striped table-advance table-hover" style="color:#000000">
				   <tbody>
					  <tr class="bg-primary">
						<th style="background-color:#003d65; color:#FFFFFF;">Sr. No.</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Department Name</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Department Location</th>
						<th style="background-color:#003d65; color:#FFFFFF;"><i class="icon_cogs"></i> Action</th>
					  </tr>

					  {% for i in departments %}
					       <tr>
                   <td>{{i.department_id}}</td>
						        <td>{{i.department_name}}</td>
						        <td>{{i.department_location}}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'listings:update_dept' i.department_id %}" class="btn btn-success">Edit</a>
                            <a class="delete-dialog btn btn-danger"  method="POST" href="{% url 'listings:delete_dept' i.department_id%}">Delete</a>
                        </div>
                    </td>
					       </tr>
					  {% endfor %}

				   </tbody>
				</table>
			  </section>
			  <input type="hidden" name="act" />
			  <input type="hidden" name="medicine_id" id="recordID" />
			 </form>
		  </div>
	  </div>
	</div>
{% endblock content %}

listings/templates/listings/projectdetails.html
{% extends 'base.html' %}
{% block content %}
<script>
$(document).on("click", ".delete-dialog", function () {
  var id = $(this).data('id');
	$("#recordID").val( id );
});
function delete_record(project_id)
{
	location.href = "/project/delete/"+$("#recordID").val();
}
</script>
    <!--breadcrumbs start-->
    <div class="banner">
      <h1 id='bannerLogo'>ALL PROJECTS</h1>
    </div>
<!-- //breadcrumbs -->

<div id='listingadd' class="container">
		<div class="row">
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
		  {% endif %}
		  <div class="col-lg-12">
			<form name="frm" action="lib/project.php" method="post">
			  <section class="panel">
				  <table class="table table-striped table-advance table-hover" style="color:#000000">
				   <tbody>
							<tr>
								<th style="background-color:#003d65; color:#FFFFFF;">ID</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Project Lead</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Project Title</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Client Name</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Submission Date</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Duration</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Email</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Department</th>
								<th style="background-color:#003d65; color:#FFFFFF;">Action</th>
							</tr>
							{% for i in projectlist %}
								<tr>
                  <td>{{i.project_id}}</td>
                  <td>{{i.project_lead_name}}</td>
									<td>{{i.project_title}}</td>
									<td>{{i.project_client_name}}</td>
									<td>{{i.project_submission_date}}</td>
									<td>{{i.project_duration}}</td>
                  <td>{{i.project_email}}</td>
									<td>{{i.project_department}}</td>
									<td>
											<div class="btn-group">
													<a href="{% url 'listings:update_project' i.project_id %}" class="btn btn-success">Edit</a>
													<a class="delete-dialog btn btn-danger"  method="POST" href="{% url 'listings:delete_project' i.project_id%}">Delete</a>
											</div>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				<input type="hidden" name="act" />
			  <input type="hidden" name="project_id" id="recordID" />
	</form>
</div>
</div>
</div>
</div>
{% endblock content %}

listings/templates/listings/statusdetails.html
{% extends 'base.html' %}
{% block content %}
<script>
$(document).on("click", ".delete-dialog", function () {
  var id = $(this).data('id');
	$("#recordID").val( id );
});
function delete_record(status_id)
{
	location.href = "/status/delete/"+$("#recordID").val();
}
</script>

    <!--breadcrumbs start-->
    <div class="banner">
      <h1 id='bannerLogo'>STATUS DETAILS</h1>
    </div>
    <!--breadcrumbs end-->

 <div id='listingadd' class="container">
		<div class="row">
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
		  {% endif %}
		  <div class="col-lg-12">
			<form name="frm" action="" method="post">
			  <section class="panel">
				  <table class="table table-striped table-advance table-hover" style="color:#000000">
				   <tbody>
					  <tr class="bg-primary">
						<th style="background-color:#003d65; color:#FFFFFF;">Sr. No.</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Status Name</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Status Description</th>
						<th style="background-color:#003d65; color:#FFFFFF;"><i class="icon_cogs"></i> Action</th>
					  </tr>


					  {% for i in statuslist %}
            <tr>
              <td>{{i.status_id}}</td>
              <td>{{i.status_title}}</td>
              <td>{{i.status_description}}</td>
              <td>
                <div class="btn-group">
                   <a href="{% url 'listings:update_status' i.status_id %}" class="btn btn-success">Edit</a>
                  <a class="delete-dialog btn btn-danger"  method="POST" href="{% url 'listings:delete_status' i.status_id%}">Delete</a>
                </div>
                </td>
            </tr>
					  {% endfor %}
				   </tbody>
				</table>
			  </section>
			  <input type="hidden" name="act" />
			  <input type="hidden" name="medicine_id" id="recordID" />
			 </form>
		  </div>
	  </div>
	</div>
{% endblock content %}

listings/templates/listings/typedetails.html
{% extends 'base.html' %}
{% block content %}
<script>
$(document).on("click", ".delete-dialog", function () {
  var id = $(this).data('id');
	$("#recordID").val( id );
});
function delete_record(type_id)
{
	location.href = "/type/delete/"+$("#recordID").val();
}
</script>

    <!--breadcrumbs start-->
    <div class="banner">
      <h1 id='bannerLogo'>TYPE DETAIL</h1>
    </div>
    <!--breadcrumbs end-->

 <div id='listingadd' class="container">
		<div class="row">
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
		  {% endif %}
		  <div class="col-lg-12">
			<form name="frm" action="" method="post">
			  <section class="panel">
				  <table class="table table-striped table-advance table-hover" style="color:#000000">
				   <tbody>
					  <tr class="bg-primary">
						<th style="background-color:#003d65; color:#FFFFFF;">Sr. No.</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Type Name</th>
						<th style="background-color:#003d65; color:#FFFFFF;">Type Description</th>
						<th style="background-color:#003d65; color:#FFFFFF;"><i class="icon_cogs"></i> Action</th>
					  </tr>
					  {% for i in typelist %}
					  <tr>
            <td>{{i.type_id}}</td>
						<td>{{i.type_title}}</td>
						<td>{{i.type_description}}</td>
						<td>
						  <div class="btn-group">
						     <a href="{% url 'listings:update_type' i.type_id %}" class="btn btn-success">Edit</a>
							  <a class="delete-dialog btn btn-danger"  method="POST" href="{% url 'listings:delete_type' i.type_title%}">Delete</a>
						  </div>
						  </td>
					  </tr>
					  {% endfor %}
				   </tbody>
				</table>
			  </section>
			  <input type="hidden" name="act" />
			  <input type="hidden" name="medicine_id" id="recordID" />
			 </form>
		  </div>
	  </div>
	</div>
{% endblock content %}