contact/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='contact'
urlpatterns = [

    path('contact',views.contact,name='contact'),

]

listings/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='listings'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
#display of info urls
    path('deptlisting',views.departments,name='deptlisting'),
    path('buglisting',views.buglist,name='buglisting'),
    path('statuslisting',views.statuslist,name='statuslisting'),
    path('typelisting',views.typelist,name='typelisting'),
    path('projectlisting',views.projectlist,name='projectlisting'),
    path('userlisting',views.userlist,name='userlisting'),
#create urls
    path('add_bug/',views.addBug,name='add_bug'),
    path('add_type/',views.addType,name='add_type'),
    path('add_status/',views.addStatus,name='add_status'),
    path('add_dept/',views.addDept,name='add_dept'),
    path('add_project/',views.addProject,name='add_project'),
    path('add_user/',views.addUser,name='add_user'),
#update urls
    path('update_bug/<str:pk>/',views.updateBug,name='update_bug'),
    path('update_type/<str:pk>/',views.updateType,name='update_type'),
    path('update_status/<str:pk>/',views.updateStatus,name='update_status'),
    path('update_project/<str:pk>/',views.updateProject,name='update_project'),
    path('update_user/<str:pk>/',views.updateUser,name='update_user'),
    path('update_dept/<str:pk>/',views.updateDept,name='update_dept'),
#delete urls
    path('delete_bug/<str:pk>/',views.deleteBug,name='delete_bug'),
    path('delete_type/<str:pk>/',views.deleteType,name='delete_type'),
    path('delete_status/<str:pk>/',views.deleteStatus,name='delete_status'),
    path('delete_project/<str:pk>/',views.deleteProject,name='delete_project'),
    path('delete_user/<str:pk>/',views.deleteUser,name='delete_user'),
    path('delete_dept/<str:pk>/',views.deleteDept,name='delete_dept'),

    ]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('contact',views.ContactPage.as_view(),name='contact'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('listings/',include('listings.urls',namespace='listings')),
    path('contact/',include('contact.urls',namespace='contact')),










    path('myaccount',views.UserAccount.as_view(),name='myaccount'),
    path('passwordchange',views.ChangePassword.as_view(),name='changepassword'),



]

templates/delete/deletebug.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete Bug?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this bug?</p>

<form class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn" class="btn btn-warning" href="{% url 'listings:buglisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>
<br>
{% endblock %}

templates/delete/deletedept.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete Department?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this Department?</p>

<form  class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn" class="btn btn-warning" href="{% url 'listings:deptlisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>

{% endblock %}

templates/delete/deleteproject.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete Project?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this project?</p>

<form  class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn" class="btn btn-warning" href="{% url 'listings:projectlisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>

{% endblock %}

templates/delete/deletestatus.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete Status?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this status?</p>

<form class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn" class="btn btn-warning" href="{% url 'listings:statuslisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>

{% endblock %}

templates/delete/deletetype.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete Type?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this type?</p>

<form class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn" class="btn btn-warning" href="{% url 'listings:typelisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>

{% endblock %}

templates/delete/deleteuser.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 id='bannerLogo'>Delete User?</h1>
</div>

<p class='deletep'>Are you sure you want to delete this user?</p>

<form class="addclass5" method="POST">

  {% csrf_token%}
  <a id="cancelbtn"class="btn btn-warning" href="{% url 'listings:userlisting'%}">Cancel</a>

  <input id='deletebtn' class="btn btn-danger" type="submit"
  onclick="return confirm('This will be removed forever. Are you sure you want to delete?');" name="Confirm" >

</form>

{% endblock %}