accounts/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views
from .views import signup, dashboard
app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', dashboard, name='dashboard'),


    path('login',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    #path('signup/', signup, name='signup'),

    ]

contact/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='contact'
urlpatterns = [

    path('contact',views.contact,name='contact'),

]

listings/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='listings'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
#display of info urls
    path('deptlisting',views.departments,name='deptlisting'),
    path('buglisting',views.buglist,name='buglisting'),
    path('statuslisting',views.statuslist,name='statuslisting'),
    path('typelisting',views.typelist,name='typelisting'),
    path('projectlisting',views.projectlist,name='projectlisting'),
    path('userlisting',views.userlist,name='userlisting'),
#create urls
    path('add_bug/',views.addBug,name='add_bug'),
    path('add_type/',views.addType,name='add_type'),
    path('add_status/',views.addStatus,name='add_status'),
    path('add_dept/',views.addDept,name='add_dept'),
    path('add_project/',views.addProject,name='add_project'),
    path('add_user/',views.addUser,name='add_user'),
#update urls
    path('update_bug/<str:pk>/',views.updateBug,name='update_bug'),
    path('update_type/<str:pk>/',views.updateType,name='update_type'),
    path('update_status/<str:pk>/',views.updateStatus,name='update_status'),
    path('update_project/<str:pk>/',views.updateProject,name='update_project'),
    path('update_user/<str:pk>/',views.updateUser,name='update_user'),
    path('update_dept/<str:pk>/',views.updateDept,name='update_dept'),
#delete urls
    path('delete_bug/<str:pk>/',views.deleteBug,name='delete_bug'),
    path('delete_type/<str:pk>/',views.deleteType,name='delete_type'),
    path('delete_status/<str:pk>/',views.deleteStatus,name='delete_status'),
    path('delete_project/<str:pk>/',views.deleteProject,name='delete_project'),
    path('delete_user/<str:pk>/',views.deleteUser,name='delete_user'),
    path('delete_dept/<str:pk>/',views.deleteDept,name='delete_dept'),

    ]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('contact',views.ContactPage.as_view(),name='contact'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('listings/',include('listings.urls',namespace='listings')),
    path('contact/',include('contact.urls',namespace='contact')),










    path('myaccount',views.UserAccount.as_view(),name='myaccount'),
    path('passwordchange',views.ChangePassword.as_view(),name='changepassword'),



]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Permission
from django.db import models

class UserProfile(AbstractUser):
    # Your other fields go here

    # Add a related_name to avoid clashes with auth.User
    groups = models.ManyToManyField(
        Permission,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to these groups.',
        related_name='user_profiles_groups',  # Add a unique related_name
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='user_profiles_permissions',  # Add a unique related_name
    )

accounts/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile

class SignUpForm(UserCreationForm):
    # You can add more fields here if needed

    class Meta:
        model = UserProfile
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import login,logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.db import connection
from .forms import SignUpForm

from django.conf import settings
from django.contrib.auth.decorators import login_required


from accounts import forms


@login_required
def dashboard(request):
    return render(request, 'accounts/templates/accounts/dashboard.html', )



class LogSuccess(CreateView):
    success_url = reverse_lazy("accounts:login")
    template_name = 'accounts/signup.html'

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:login')  # Redirect to the home page after successful signup
    else:
        form = SignUpForm()

    return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %} {% block content %}

<div class="banner">
  <h1 class="col-lg-4 col-sm-4" id='bannerLogo'>DASHBOARD</h1>
</div>

<style>
.dashboard .btn-circle {
  width: 156px;
  height: 156px;
  text-align: center;
  padding: 6px 0;
  line-height: 1.42;
  border-radius: 90px;
  color: #fff;
  background: #003d65;
  background-color: #003d65;
  font-size: 18px;
  font-weight: 700;
  padding-bottom: 100px;
}
.btn-circle div{
  margin-top: 40px;

}
.mydash {
	border:1px solid #003d65;
	padding:10px;
	margin:10px;
}
.col-lg-2 {
	width:14.667%;
}


</style>




	<!--breadcrumbs end-->
	<div  id ="dashboard" class="container w">
			<div class="row dashboard">
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:buglisting'%}" class="btn btn-default btn-circle"><div>Bug<br>Report</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:typelisting'%}" class="btn btn-default btn-circle"><div>Bug Type<br>Report</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:statuslisting'%}" class="btn btn-default btn-circle"><div>Status<br>Report</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:projectlisting'%}" class="btn btn-default btn-circle"><div>Project<br>Report</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:userlisting'%}" class="btn btn-default btn-circle"><div>Users<br>Report</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:add_bug'%}" class="btn btn-default btn-circle"><div>Add<br>Bug</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:add_user'%}" class="btn btn-default btn-circle"><div>Add<br>Users</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:add_project'%}" class="btn btn-default btn-circle"><div>Add<br>Project</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:add_status'%}" class="btn btn-default btn-circle"><div>Add<br>Status</div></a>
				</div><!--/.col-->
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'listings:add_type'%}" class="btn btn-default btn-circle"><div>Add<br>Bug Type</div></a>
				</div><!--/.col-->
		
				<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 mydash">
					<a href="{% url 'accounts:logout'%}" onclick="return confirm('Are you sure to logout?');" class="btn btn-default btn-circle"><div style="margin-top:55px">Logout</div></a>
				</div><!--/.col-->
			</div><!-- row -->
	</div>
	<br>
	<!-- container -->
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="banner">
  <h1 id="bannerLogo">Login</h1>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <div class="credentials-container bg-light p-3 rounded">
        <h2 class="text-muted">This website is just a prototype so you recruiters can see what it does!</h2>
        <p class="text-muted">Enter temp login credentials listed below:</p>
        <p><strong>Username:</strong> recruiter_user</p>
        <p><strong>Password:</strong> recruiter_password</p>
      </div>
    </div>
    <div class="col-md-6">
      <form id="loginid" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary mt-3" value="Login">
      </form>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
<!-- signup.html -->
{% extends 'base.html' %}

{% block content %}
<div class="banner">
    <h1 id="bannerLogo">Sign Up</h1>
  </div>
<form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Sign Up</button>
</form>
{% endblock %}