accounts/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views
from .views import signup, dashboard
app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', dashboard, name='dashboard'),


    path('login',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    #path('signup/', signup, name='signup'),

    ]

contact/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='contact'
urlpatterns = [

    path('contact',views.contact,name='contact'),

]

listings/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib import admin

app_name='listings'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
#display of info urls
    path('deptlisting',views.departments,name='deptlisting'),
    path('buglisting',views.buglist,name='buglisting'),
    path('statuslisting',views.statuslist,name='statuslisting'),
    path('typelisting',views.typelist,name='typelisting'),
    path('projectlisting',views.projectlist,name='projectlisting'),
    path('userlisting',views.userlist,name='userlisting'),
#create urls
    path('add_bug/',views.addBug,name='add_bug'),
    path('add_type/',views.addType,name='add_type'),
    path('add_status/',views.addStatus,name='add_status'),
    path('add_dept/',views.addDept,name='add_dept'),
    path('add_project/',views.addProject,name='add_project'),
    path('add_user/',views.addUser,name='add_user'),
#update urls
    path('update_bug/<str:pk>/',views.updateBug,name='update_bug'),
    path('update_type/<str:pk>/',views.updateType,name='update_type'),
    path('update_status/<str:pk>/',views.updateStatus,name='update_status'),
    path('update_project/<str:pk>/',views.updateProject,name='update_project'),
    path('update_user/<str:pk>/',views.updateUser,name='update_user'),
    path('update_dept/<str:pk>/',views.updateDept,name='update_dept'),
#delete urls
    path('delete_bug/<str:pk>/',views.deleteBug,name='delete_bug'),
    path('delete_type/<str:pk>/',views.deleteType,name='delete_type'),
    path('delete_status/<str:pk>/',views.deleteStatus,name='delete_status'),
    path('delete_project/<str:pk>/',views.deleteProject,name='delete_project'),
    path('delete_user/<str:pk>/',views.deleteUser,name='delete_user'),
    path('delete_dept/<str:pk>/',views.deleteDept,name='delete_dept'),

    ]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from tracker import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('contact',views.ContactPage.as_view(),name='contact'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('listings/',include('listings.urls',namespace='listings')),
    path('contact/',include('contact.urls',namespace='contact')),










    path('myaccount',views.UserAccount.as_view(),name='myaccount'),
    path('passwordchange',views.ChangePassword.as_view(),name='changepassword'),



]

templates/models.py
from django.db import models
from django.contrib.auth.models import User


class Contact(models.Model):
    id_number =status_id = models.AutoField(primary_key=True)
    Name= models.CharField(max_length=255, default = '',)
    email = models.CharField(max_length=255, default = '',)
    phone = models.CharField(max_length=255, default = '')
    message = models.CharField(max_length=255, default = '')
    def __str__(self):
        return self.id_number

templates/about.html
{% extends 'base.html'%}
{% block content %}
<div class="banner">
  <h1 class="slidein" id='bannerLogo'>ABOUT</h1>
</div>



<div id='aboutpic'class="container ">
  <img src="/static/bugtracker/media/1.jpg" alt="notfound">
</div>

<div class="container ">
  <div id='rightbox'class='col-lg-6 col-md-12 col-sm-12 float-lg-right float-md-right'>
    <h1 id='abouth1'><strong>About Bug Tracking System</strong></h1>
    <p></p>
    <h4 id="abouttext">The bug tracking system (also known as: ITS, trouble bug system, support bug, request managment or incident bug system) is a
    computer software package that manages and maintains lists of bugs, as needed by an organization, bug tracking systems are commonly used in an organizations customer support call center
  to create, update, and resolve reported customer bugs, or even bugs reported by that organzations other employees.
  A support bug should include vital information for the account involed and the bug encountered. This system also contains
  knowledge base containing information on each customer, resoultuions to common problems and other such data. Consisistent use of an bug tracking system is considered one of the "hallmarks of a good software
  team"</h4>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="description" content="Developed By Andre Grandon">
  	<meta name="author" content="cosmic">
  	<meta name="keywords" content="Bootstrap 3, Template, Theme, Responsive, Corporate, Business">
    <link rel="icon" type="image/png" href="http://www.example.com/image.png"><!-- Major Browsers -->
    <link rel="shortcut icon" href="{% static 'bugtracker/media/favicon.ico' %}" />
    <title>
      Bug Tracking System
    </title>


    <!-- Bootstrap CSS JS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{% static 'bugtracker/css/master.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&family=Poppins:wght@300&family=Source+Sans+Pro:wght@200&display=swap" rel="stylesheet">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-5" role="navigation" id="navbar">
      <div class="container">
          <a id="brand" class="navbar-brand mb-0 h1" href="{% url 'home' %}">Bug Tracking System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                      <a class="nav-item nav-link" id="navtext" href="{% url 'home' %}" class="btn btn-simple">Home</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'about' %}" class="btn btn-simple">About</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'accounts:dashboard' %}" class="btn btn-simple">Dashboard</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'listings:add_bug' %}" class="btn btn-simple">Add Bug</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'listings:buglisting' %}" class="btn btn-simple">Bug Reports</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'accounts:logout' %}"  onclick="return confirm('Are you sure to logout?');" class="btn btn-simple">Log out</a>
                  {% else %}
                      <a class="nav-item nav-link" id="navtext" href="{% url 'home' %}" class="btn btn-simple">Home</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'about' %}" class="btn btn-simple">About</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'accounts:login' %}" class="btn btn-simple">Login</a>
                      <a class="nav-item nav-link" id="navtext" href="{% url 'contact:contact' %}" class="btn btn-simple">Contact Us</a>
                  {% endif %}
              </div>
          </div>
      </div>
  </nav>
  
        </div>
      </div>




    <div>
      {% block content %}

      {% endblock %}

    </div>

    <!--footer start-->
    <div class="flex-wrapper">




    </div >
    <div style="clear: both">

    </div>
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-6 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
            <h2 id='footh1'>
            CONTACT INFO
          </h2>
            <address>
              <p><i class="fa fa-home pr-10"></i>Address: No.XXXXXX street</p>
              <p><i class="fa fa-globe pr-10"></i>Toronto, CA </p>
              <p><i class="fa fa-mobile pr-10"></i>Mobile : (123) 456-7890 </p>
              <p><i class="fa fa-phone pr-10"></i>Phone : (123) 456-7890 </p>
              <p><i class="fa fa-envelope pr-10"></i>Email : <a href="javascript:;">22agrandon@gmail.com</a></p>
            </address>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
              <h2 id='footh1'>MODULES</h1>
              <ul class="page-footer-list">
                {% if user.is_authenticated %}
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'listings:buglisting' %}">Bug Report Module</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'listings:projectlisting' %}">Project Report</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'listings:userlisting' %}">User Report</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'accounts:dashboard' %}">Dashboard Module</a>
                </li>
                {% else %}
                  <li>
                    <i class="fa fa-angle-right"></i>
                    <a href="{% url 'accounts:login' %}">User Module</a>
                  </li>
                  <li>
                    <i class="fa fa-angle-right"></i>
                    <a href="{% url 'accounts:login' %}">Report Module</a>
                  </li>
                  <li>
                    <i class="fa fa-angle-right"></i>
                    <a href="{% url 'accounts:login' %}">Project Report</a>
                  </li>
                  <li>
                    <i class="fa fa-angle-right"></i>
                    <a href="{% url 'accounts:login' %}">Dashboard Module</a>
                  </li>
                  {% endif %}
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
              <h2 id='footh1'>PROJECT LINKS</h2>
              <ul class="page-footer-list">
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'about' %}">About Us</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'contact:contact' %}">Contact</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="https://andregrandon-portfolio-e30b590e26c4.herokuapp.com" >Andre Personal Website</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6">
            <div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
              <h2 id='footh1'>
                ABOUT
              </h2>
              <p>A bug element, within an bug tracking system, is a running report on a particular problem, its status, and other relevant data. They are commonly created in a help desk or call center environment and almost always have a unique reference number, also known as a case</p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- footer end -->

    <script src="{% static 'bugtracker/js/master.js' %}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  </body>
</html>

templates/changepassword.html
{% extends 'base.html' %} {% block content %}
<!--breadcrumbs start-->
<div class="banner">
  <h1 id='bannerLogo'>CHANGE PASSWORD</h1>
</div>
<!--breadcrumbs end-->

<!--container start-->
<div class="registration-bg">
	<div class="container">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
		<form method="post" class="form-signin wow fadeInUp" id="changepass" style="max-width:800px">
			{% csrf_token %}
			<h2 class="form-signin-heading">Change Password</h2>
			{% if messages %}
				<div class="alert alert-success fade in" style="margin:10px;">
					{% for message in messages %}
						<strong>{{ message }}</strong>
					{% endfor %}
				</div>
			{% endif %}
			<div class="login-wrap">
				<div class="form-group">
					<label for="pwd">New Password</label>
					<input type="password" class="form-control" placeholder="New Password" required autofocus="" name="user_new_password" id="user_new_password">
				</div>
				<div class="form-group">
					<label for="pwd">Confirm Password</label>
					<input type="password" class="form-control" placeholder="Confirm Password" required autofocus="" name="user_confirm_password" id="user_confirm_password">
				</div>
				<div class="form-group" style="text-align:right;">
					<button class="btn btn-lg btn-login btn-block" type="submit" style="width:200px;">Change Password</button>
				</div>
			</div>
			<input type="hidden" name="act" value="change_password">
		</form>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>


	</div>
 </div>

{%endblock%}

templates/index.html
{% extends 'base.html' %}
{% block content %}


<div class="main">
  <img id="main" src="/static/bugtracker/media/main.jpeg" alt="NotFound">
</div>
    <!-- Sequence Modern Slider -->

<div id='indextext'>
  <h1 ><strong><em><center>Welcome To Bug Tracking System</center></em></strong></h1>
</div>


<div class="row">
  <div class="column">
    <img id= "picshome" src="/static/bugtracker/media/1.jpg" alt="Notfound" style="width:100%;">
    <h4 id="welcomebanner">Bug Tracking System</h4>
    <p id='welcometext' class="col-lg-12 col-sm-12 col-xs-12">The bug tracking system (also known as: ITS, trouble bug system, support bug, request managment or incident bug system) is a
    computer software package that manages and maintains lists of bugs.</p>
  </div>
  <div class="column">
    <img  id= "picshome"src="/static/bugtracker/media/2.jpg" alt="NotFound" style="width:100%;">
    <h4 id="welcomebanner">User Management System</h4>
    <p id='welcometext' class="col-lg-12 col-sm-12 col-xs-12">The bug tracking system (also known as: ITS, trouble bug system, support bug, request managment or incident bug system) is a
    computer software package that manages and maintains lists of bugs.</p>
  </div>
  <div class="column" >
    <img id= "picshome" src="/static/bugtracker/media/3.png" alt="Notfound" style="width:90%;">
    <h4 id="welcomebanner">Bug Management System</h4>
    <p id='welcometext' class="col-lg-12 col-sm-12 col-xs-12">The bug tracking system (also known as: ITS, trouble bug system, support bug, request managment or incident bug system) is a
    computer software package that manages and maintains lists of bugs.</p>
  </div>
</div>

<div class="properties gray-bg">
  <div class="container2">
    <div class="row">
      <div class="col-lg-6 col-sm-6 text-center wow fadeInLeft">
        <img src="/static/bugtracker/media/5.jpg" alt="notfound" ">
      </div>
      <div  class="col-lg-6 col-sm-6 wow fadeInRight">
        <h1>
          About Bug Tracking System
        </h1>
        <hr>
        <p>A bug element, within an bug tracking system, is a running report on a particular problem, its status, and other relevant data. They are commonly created in a help desk or call center environment and almost always have a unique reference number, also known as a case, bug or call log number which is used to allow the user or help staff to quickly locate, add to or communicate the status of the user's bug or request.</p>
        <p>
          These bugs are so called because of their origin as small cards within a traditional wall mounted work planning system when this kind of support started. Operators or staff receiving a call or query from a user would fill out a small card with the user's details and a brief summary of the request and place it into a position (usually the last) in a column of pending slots for an appropriate engineer, so determining the staff member who would deal with the query and the priority of the request.
          </p>
        <hr>
      </div>
    </div>
  </div>
</div>


{%endblock%}

templates/newstatus.html
{% extends 'base.html' %} {% block content %}
<script>
	jQuery(function () {
		jQuery("#appointment_date").datepicker({
			changeMonth: true,
			changeYear: true,
			yearRange: "0:+1",
			dateFormat: 'd MM,yy'
		});
	});
</script>


<div class="banner">
  <h1 id='bannerLogo'>ADD STATUS</h1>
</div>
<!--breadcrumbs end-->

<!--container start-->
<div class="typo">
  <div class="container">
    <div class="typo-grids">
      <center>
        <div class="registration-bg">
          <div class="row">
            <form enctype="multipart/form-data" method="post" class="form-signin wow fadeInUp" action="" style="max-width:60%">
              {% csrf_token %}
              <h2 class="form-signin-heading">
                {% if fn == "add" %}
                  Add New Status
                {% elif fn == "update" %}
                  Update Status
                {% endif %}
              </h2>
              {% if messages %}
                <div class="alert alert-success fade in" style="margin:10px;">
                  {% for message in messages %}
                    <strong>{{ message }}</strong>
                  {% endfor %}
                </div>
              {% endif %}
              <div class="login-wrap">



                <div class="col-xs-6 form-group">
                  <label for="pwd">Status Name</label>
                  <input type="text" value="{{statusDetails.status_title}}" name="status_title" id="status_title" class="form-control" placeholder="Status Name" required>
                </div>


                <div class="col-xs-6 form-group" style="clear:both">
                  <label for="pwd">Description of the Status</label>
                  <textarea class="form-control" style="height:150px;" placeholder="Description" autofocus="" name="status_description" id="status_description" required>{{statusDetails.status_description}}</textarea>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">Submit</button>
              </div>
              <input type="hidden" name="act" value="save_status">
              <input type="hidden" name="user_id" value="{{statuslist.status_id}}">
            </form>
          </div>
        </div>
      </center>
    </div>
  </div>
</div>

<!--container end-->
{% endblock content %}

templates/user.html
{% extends 'base.html' %} {% block content %}
<script>
	jQuery(function () {
		jQuery("#user_dob").datepicker({
			changeMonth: true,
			changeYear: true,
			yearRange: "0:+1",
			dateFormat: 'd MM,yy'
		});
	});
</script>
<!--breadcrumbs start-->
<div class="banner">
  <h1 id='bannerLogo'>ADMIN MANAGEMENT</h1>
</div>
<!--breadcrumbs end-->

<!--container start-->
<div class="typo">
  <div class="container">
    <div class="typo-grids">
      <center>
        <div class="registration-bg">
        	<div class="row">
        		<form enctype="multipart/form-data" method="post" class="form-signin wow fadeInUp" action="" style="max-width:60%">
        			{% csrf_token %}
              <div class="col-sm-1">&nbsp;</div>
        			<h2 class="form-signin-heading">
        				{% if fn == "add" %}
        					Add {{sub_heading}}
        				{% elif fn == "update" %}
        					{{sub_heading}}
        				{% else %}
        					My Profile
        				{% endif %}
        			</h2>
        			{% if messages %}
        				<div class="alert alert-success fade in" style="margin:10px;">
        					{% for message in messages %}
        						<strong>{{ message }}</strong>
        					{% endfor %}
        				</div>
        			{% endif %}
        			<div class="login-wrap">
        				<div class="col-xs-6 form-group">
        					<label for="pwd">Select User Role</label>
        					<select name="user_level_id" required class="form-control" placeholder="Select Role" autofocus="" />
        					<option value="">Please Select</option>
        					{% for role in rolelist %}
        					<option value="{{ role.role_id }}" {% ifequal role.role_id userdetails.user_level_id %} selected="selected"{% endifequal %}>{{role.role_title}}</option>
        					{% endfor %}
        					</select>
        				</div>
        				<div style="clear: both; border: 1px solid #CCCCCC;"></div><br>

        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Name</label>
        					<input type="text" class="form-control" placeholder="User Name" autofocus="" name="user_name" id="user_name" value="{{userdetails.user_name}}">
        				</div>

        				<div class="col-xs-6 form-group">
        					<label for="pwd">Login ID</label>
        					<input type="text" class="form-control" placeholder="Username" autofocus="" name="user_username" id="user_username" value="{{userdetails.user_username}}">
        				</div>
        				<div class="col-xs-6 form-group update-user">
        					<label for="pwd">Password</label>
        					<input type="password" class="form-control" placeholder="Password" autofocus="" name="user_password" id="user_password" value="{{userdetails.user_password}}">
        				</div>
        				<div class="col-xs-6 form-group update-user">
        					<label for="pwd">Confirm Password</label>
        					<input type="password" class="form-control" placeholder="Confirm Password" autofocus="" name="user_confirm_password" id="user_confirm_password" value="{{userdetails.user_password}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label>Gender {{userdetails.user_gender}}</label>
        					<span class="form-control">
        						<input type="radio" class="radio-inline" name="user_gender" value="Male" {% ifequal userdetails.user_gender 'Male' %} checked="checked"{% endifequal %} required> Male &nbsp&nbsp
        						<input type="radio" class="radio-inline" name="user_gender" value="Female" {% ifequal userdetails.user_gender 'Female' %} checked="checked"{% endifequal %} required> Female
        					</span>
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Email</label>
        					<input type="text" class="form-control" placeholder="User Email" autofocus="" name="user_email" id="user_email" value="{{userdetails.user_email}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Mobile</label>
        					<input type="text" class="form-control" placeholder="User Mobile" autofocus="" name="user_mobile" id="user_mobile" value="{{userdetails.user_mobile}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Date of Birth</label>
        					<input type="text" class="form-control" placeholder="User Date of Birth" autofocus="" id="user_dob" name="user_dob" value="{{userdetails.user_dob}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Address Line 1</label>
        					<input type="text" class="form-control" placeholder="User Address Line 1" autofocus="" name="user_add1" id="user_date" value="{{userdetails.user_add1}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Address Line 2</label>
        					<input type="text" class="form-control" placeholder="User Address Line 2" autofocus="" name="user_add2" id="user_add2" value="{{userdetails.user_add2}}">
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User City</label>
        					<select name="user_city" required class="form-control" placeholder="Select User" autofocus="" />
        					<option value="">Please Select</option>
        					{% for city in citylist %}
        					<option value="{{ city.city_id }}" {% ifequal city.city_id userdetails.user_city %} selected="selected"{% endifequal %}>{{city.city_name}}</option>
        					{% endfor %}
        					</select>
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User State</label>
        					<select name="user_state" required class="form-control" placeholder="Select Month" autofocus="" />
        					<option value="">Please Select</option>
        					{% for state in statelist %}
        					<option value="{{ state.state_id }}" {% ifequal state.state_id userdetails.user_state %} selected="selected"{% endifequal %}>{{state.state_name}}</option>
        					{% endfor %}
        					</select>
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Country</label>
        					<select name="user_country" required class="form-control" placeholder="Select Month" autofocus="" />
        					<option value="">Please Select</option>
        					{% for country in countrylist %}
        					<option value="{{ country.country_id }}" {% ifequal country.country_id userdetails.user_country %} selected="selected"{% endifequal %}>{{country.country_name}}</option>
        					{% endfor %}
        					</select>
        				</div>
        				<div class="col-xs-6 form-group">
        					<label for="pwd">User Picture</label>
        					<input type="file" accept="image/*" class="form-control" placeholder="User Mobile" autofocus="" name="user_image" id="user_image"
        					 value="{{userdetails.user_image}}">
        					{% if userdetails.user_image %}
        					<div class="clearfix" style="margin-top:20px;"><img src="{{userdetails.user_image}}" style="width: 100px"></div><br>
        					{% endif %}
        				</div>
        				<button class="btn btn-lg btn-login btn-block" type="submit">Submit</button>
        			</div>
        			<input type="hidden" name="act" value="save_user">
        			<input type="hidden" name="avail_image" value="{{userdetails.user_image}}">
        			<input type="hidden" name="user_id" value="{{userdetails.user_id}}">
              <div class="col-sm-1">&nbsp;</div>
              <div class="col-sm-1">&nbsp;</div>

        		</form>
        	</div>
        </div>
      </center>
    </div>
  </div>
</div>






<!--container end-->
{% endblock content %}